### ISSUE TITLE
Create glossary for AVR pinouts by parsing datasheets

### ISSUE THREAD

**Issue by macbre** [elecena/parts-metadata#18]
http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-2543-AVR-ATtiny2313_Datasheet.pdf

### Alternate Port Functions

> • OC0A/PCINT2 – Port B, Bit 2
OC0A: Output Compare Match A output. The PB2 pin can serve as an external output for the
Timer/Counter0 Output Compare A. The pin has to be configured as an output (DDB2 set (one))
to serve this function. The OC0A pin is also the output pin for the PWM mode timer function.
PCINT2: Pin Change Interrupt Source 2. The PB2 pin can serve as an external interrupt source.
• AIN1/PCINT1 – Port B, Bit 1
AIN1: Analog Comparator Negative input. Configure the port pin as input with the internal pull-up
switched off to avoid the digital port function from interfering with the function of the analog
comparator.
PCINT1: Pin Change Interrupt Source 1. The PB1 pin can serve as an external interrupt source

> USCK: Three-wire mode Universal Serial Interface Clock.
SCL: Two-wire mode Serial Clock for USI Two-wire mode.
PCINT7: Pin Change Interrupt source 7. The PB7 pin can serve as an external interrupt source

> DI: Three-wire mode Universal Serial Interface Data input. Three-wire mode does not override
normal port functions, so pin must be configured as an input. SDA: Two-wire mode Serial Inter-
face Data.

```
AIN1: Analog Comparator Negative input. Configure the port pin as input with the internal pull-up
switched off to avoid the digital port function from interfering with the function of the analog
comparator.
```

### `glossary.yml`

```yaml
- pins:
  - name: AIN1
    description: Analog Comparator Negative input. Configure the port pin as input with the internal pull-up
switched off to avoid the digital port function from interfering with the function of the analog
comparator
```
